//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSaveBackup.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSaveBackup.Lang.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists on Google Drive.
        /// </summary>
        internal static string alreadyExistsOnGoogleDrive {
            get {
                return ResourceManager.GetString("alreadyExistsOnGoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Information.
        /// </summary>
        internal static string applicationInformationToolStripMenuItem {
            get {
                return ResourceManager.GetString("applicationInformationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string areYouSure {
            get {
                return ResourceManager.GetString("areYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto back up game save after you close the game.
        /// </summary>
        internal static string autoDL {
            get {
                return ResourceManager.GetString("autoDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto download and restore on game start.
        /// </summary>
        internal static string autoRestore {
            get {
                return ResourceManager.GetString("autoRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto uploading.
        /// </summary>
        internal static string autoUpload {
            get {
                return ResourceManager.GetString("autoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup save folder for.
        /// </summary>
        internal static string creatingSaveFolder {
            get {
                return ResourceManager.GetString("creatingSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating zip backup....
        /// </summary>
        internal static string creatingZip {
            get {
                return ResourceManager.GetString("creatingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currently backed up.
        /// </summary>
        internal static string currentlyBackedUp {
            get {
                return ResourceManager.GetString("currentlyBackedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currently running..
        /// </summary>
        internal static string currentlyRunning {
            get {
                return ResourceManager.GetString("currentlyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export debug console data to file.
        /// </summary>
        internal static string debugExport {
            get {
                return ResourceManager.GetString("debugExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Cloud file.
        /// </summary>
        internal static string deletedFile {
            get {
                return ResourceManager.GetString("deletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Cloud Delete File.
        /// </summary>
        internal static string deleteTitle {
            get {
                return ResourceManager.GetString("deleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected supported game.
        /// </summary>
        internal static string detectedGame {
            get {
                return ResourceManager.GetString("detectedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Cannot pull XML data from dropbox.
        /// </summary>
        internal static string dlError {
            get {
                return ResourceManager.GetString("dlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new GOG XML data file.
        /// </summary>
        internal static string dlGOGXML {
            get {
                return ResourceManager.GetString("dlGOGXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new Steam XML data file.
        /// </summary>
        internal static string dlSteamXML {
            get {
                return ResourceManager.GetString("dlSteamXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD / RESTORE.
        /// </summary>
        internal static string downloadBtn {
            get {
                return ResourceManager.GetString("downloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File did not upload!.
        /// </summary>
        internal static string errorUploading {
            get {
                return ResourceManager.GetString("errorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Service is null in checkCloudSaves.
        /// </summary>
        internal static string errServiceNull {
            get {
                return ResourceManager.GetString("errServiceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string fileDoesntExist {
            get {
                return ResourceManager.GetString("fileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Save Backup.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Google Cloud?.
        /// </summary>
        internal static string fromCloud {
            get {
                return ResourceManager.GetString("fromCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Google Cloud....
        /// </summary>
        internal static string fromGoogleCloud {
            get {
                return ResourceManager.GetString("fromGoogleCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game auto detection and backup.
        /// </summary>
        internal static string gameBackupMsg {
            get {
                return ResourceManager.GetString("gameBackupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: If you do not see a game detected, it&apos;s because the XML data doesn&apos;t exist yet!.
        /// </summary>
        internal static string gameDetectMsg {
            get {
                return ResourceManager.GetString("gameDetectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game save restored from cloud, resuming game....
        /// </summary>
        internal static string gameRestored {
            get {
                return ResourceManager.GetString("gameRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game save..
        /// </summary>
        internal static string gameSave {
            get {
                return ResourceManager.GetString("gameSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game data loading completed!.
        /// </summary>
        internal static string gDataLoadComplete {
            get {
                return ResourceManager.GetString("gDataLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting cloud folder id....
        /// </summary>
        internal static string getFolderID {
            get {
                return ResourceManager.GetString("getFolderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game data loading completed!.
        /// </summary>
        internal static string getMoveDirComplete {
            get {
                return ResourceManager.GetString("getMoveDirComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting game process ID....
        /// </summary>
        internal static string gettingProc {
            get {
                return ResourceManager.GetString("gettingProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently using the newest GOG XML data file..
        /// </summary>
        internal static string goodGOGXML {
            get {
                return ResourceManager.GetString("goodGOGXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently using the newest Steam XML data file..
        /// </summary>
        internal static string goodSteamXML {
            get {
                return ResourceManager.GetString("goodSteamXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive Folder List.
        /// </summary>
        internal static string googleDriveFolderListToolStripMenuItem {
            get {
                return ResourceManager.GetString("googleDriveFolderListToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now setting up initial GameBackup folder....
        /// </summary>
        internal static string googlesetup {
            get {
                return ResourceManager.GetString("googlesetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit max number of uploads, deleting.
        /// </summary>
        internal static string hitMax {
            get {
                return ResourceManager.GetString("hitMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installed on computer..
        /// </summary>
        internal static string installed {
            get {
                return ResourceManager.GetString("installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string langLabel {
            get {
                return ResourceManager.GetString("langLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still loading game data, please wait....
        /// </summary>
        internal static string loadingGamesWait {
            get {
                return ResourceManager.GetString("loadingGamesWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating game directory....
        /// </summary>
        internal static string locatingDir {
            get {
                return ResourceManager.GetString("locatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Backups.
        /// </summary>
        internal static string mbLabel {
            get {
                return ResourceManager.GetString("mbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray on startup.
        /// </summary>
        internal static string miniStartup {
            get {
                return ResourceManager.GetString("miniStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Save Backup in System Tray.
        /// </summary>
        internal static string miniToTray {
            get {
                return ResourceManager.GetString("miniToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing some required save files for backup..
        /// </summary>
        internal static string missingFiles {
            get {
                return ResourceManager.GetString("missingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Google Drive Steam Save Backups.
        /// </summary>
        internal static string myDriveBackupsTitle {
            get {
                return ResourceManager.GetString("myDriveBackupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has stopped running. Need to do a backup....
        /// </summary>
        internal static string needToBackup {
            get {
                return ResourceManager.GetString("needToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No GOG game directories given. Open settings and add some..
        /// </summary>
        internal static string noGOGGames {
            get {
                return ResourceManager.GetString("noGOGGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Google Drive.
        /// </summary>
        internal static string onGoogleDrive {
            get {
                return ResourceManager.GetString("onGoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer Information.
        /// </summary>
        internal static string programmerToolStripMenuItem {
            get {
                return ResourceManager.GetString("programmerToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created for Steam game save file backup and restore..
        /// </summary>
        internal static string purpose {
            get {
                return ResourceManager.GetString("purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry keys restored!.
        /// </summary>
        internal static string regKeysRestored {
            get {
                return ResourceManager.GetString("regKeysRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart program if you change settings..
        /// </summary>
        internal static string restartLabel {
            get {
                return ResourceManager.GetString("restartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring registry keys....
        /// </summary>
        internal static string restoreRegKeys {
            get {
                return ResourceManager.GetString("restoreRegKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring file/folder.
        /// </summary>
        internal static string restoring {
            get {
                return ResourceManager.GetString("restoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup.
        /// </summary>
        internal static string restoringBackup {
            get {
                return ResourceManager.GetString("restoringBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string settingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Content Libraries.
        /// </summary>
        internal static string steamLabel {
            get {
                return ResourceManager.GetString("steamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspending game while we restore the newest cloud backup..
        /// </summary>
        internal static string suspending {
            get {
                return ResourceManager.GetString("suspending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD / BACKUP.
        /// </summary>
        internal static string uploadBtn {
            get {
                return ResourceManager.GetString("uploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading zip backup....
        /// </summary>
        internal static string uploadingZip {
            get {
                return ResourceManager.GetString("uploadingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful with file ID.
        /// </summary>
        internal static string upoadSuccess {
            get {
                return ResourceManager.GetString("upoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit drive.google.com.
        /// </summary>
        internal static string visitDrivegooglecomToolStripMenuItem {
            get {
                return ResourceManager.GetString("visitDrivegooglecomToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        internal static string visitNewagesoldiercomToolStripMenuItem {
            get {
                return ResourceManager.GetString("visitNewagesoldiercomToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to GameSaveBackup using free cloud storage services!.
        /// </summary>
        internal static string welcomeMsg {
            get {
                return ResourceManager.GetString("welcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it closes, we will do a backup to your cloud storage automatically!.
        /// </summary>
        internal static string whenClosing {
            get {
                return ResourceManager.GetString("whenClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start program on Windows startup.
        /// </summary>
        internal static string winstartup {
            get {
                return ResourceManager.GetString("winstartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: XML file missing and cannot download from DropBox!.
        /// </summary>
        internal static string xmlFatal {
            get {
                return ResourceManager.GetString("xmlFatal", resourceCulture);
            }
        }
    }
}
